# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    robot1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot1_controller:
  ros__parameters:
    joints:
      - remus_joint_a1
      - remus_joint_a2
      - remus_joint_a3
      - remus_joint_a4
      - remus_joint_a5
      - remus_joint_a6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true