# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    kuka_kvp_hw_interface:
      type: kuka_kvp_hw_interface/KukaKvpHardwareInterface
      # Ajoutez ici vos paramètres spécifiques

kuka_kvp_hw_interface:
  ros__parameters:
    joints:
      - remus_joint_a1
      - remus_joint_a2
      - remus_joint_a3
      - remus_joint_a4
      - remus_joint_a5
      - remus_joint_a6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true