# Example command:
#   Humble on a NVIDIA system:
#   DOCKER_IMAGE=humble-humble-tutorial-source docker compose run gpu
#   DOCKER_IMAGE=main-jazzy-tutorial-source docker-compose run gpu
#   ros2 launch moveit2_tutorials demo.launch.py
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=main-rolling-tutorial-source compose run cpu

services:
  cpu:
    image: moveit/moveit2:${DOCKER_IMAGE}
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: ["/entrypoint.sh"]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - /home/lolo/kukaros/src:/root/ws_moveit/src
      - /home/lolo/kukaros/docker-images/moveit_kr210/entrypoint.sh:/entrypoint.sh
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
  gpu:
    image: moveit/moveit2:${DOCKER_IMAGE}
    container_name: moveit2_container
    privileged: true
    network_mode: host
    ports:
      - "8765:8765"
    command: ["/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - /home/lolo/kuka/kukaros/src:/root/ws_moveit/src
      - /home/lolo/kuka/kukaros/docker-images/moveit_kr210/entrypoint.sh:/entrypoint.sh
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
